# -*- coding: utf-8 -*-
import json


if __name__ == "__main__":

    nombres_administradoras = {
        "SECURITY": "ADMINISTRADORA GENERAL DE FONDOS  SECURITY S.A.",
        "SURA": "ADMINISTRADORA GENERAL DE FONDOS SURA S.A.",
        "BANCHILE": "BANCHILE ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "BANCOESTADO": "BANCOESTADO S.A. ADMINISTRADORA  GENERAL DE FONDOS",
        "BANCO_INTERNACIONAL": "BANCO INTERNACIONAL ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "BCI": "BCI ASSET MANAGEMENT ADMINISTRADORA  GENERAL DE FONDOS S.A.",
        "BICE": "BICE INVERSIONES ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "BTG_PACTUAL": "BTG PACTUAL CHILE S.A. ADMINISTRADORA GENERAL DE FONDOS",
        "COMPASS": "COMPASS GROUP CHILE S.A. ADMINISTRADORA GENERAL DE FONDOS",
        "CREDICORP": "CREDICORP CAPITAL ASSET MANAGEMENT S.A. ADMINISTRADORA GENERAL DE FONDOS",
        "FINTUAL": "FINTUAL ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "ITAU": "ITAU ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "LARRAINVIAL": "LARRAINVIAL ASSET MANAGEMENT ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "PRINCIPAL": "PRINCIPAL  ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "SANTANDER": "SANTANDER ASSET MANAGEMENT S.A. ADMINISTRADORA GENERAL DE FONDOS",
        "SCOTIA": "SCOTIA  ADMINISTRADORA GENERAL DE FONDOS CHILE S.A.",
        "SCOTIA_AZUL": "SCOTIA AZUL ASSET MANAGEMENT ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "TOESCA": "TOESCA S.A.  ADMINISTRADORA GENERAL DE FONDOS",
        "ZURICH": "ZURICH ADMINISTRADORA GENERAL DE FONDOS S.A.",
        "ZURICH_CHILE": "ZURICH CHILE ASSET MANAGEMENT ADMINISTRADORA GENERAL DE FONDOS S.A.",
    }

    print(json.dumps(nombres_administradoras, indent=4))
